---
- name: "Enable and check monitoring on API Managers"
  hosts: managers
  gather_facts: False

  tasks:
    - name: "Enable SNMP"
      raw: "mgmt snmp set on"
      register: snmp_cmd
    - debug: var=snmp_cmd

    - name: "Get SNMP Status"
      raw: "mgmt snmp show status"
      changed_when: False
      register: result
    - debug: var=result
    - name: "Test SNMP Active"
      assert:
        that:
          - "'Status: on' in result.stdout"
